### Load lib.

In [11]:
import pandas as pd
import matplotlib.pyplot as plt

### load data

In [12]:
data = pd.read_csv("steam-200k.csv")

In [13]:
data.columns =["user_id","game_title","ownership_type","hours_played","x"]

In [14]:
data.head()

     user_id                  game_title ownership_type  hours_played  x
0  151603712  The Elder Scrolls V Skyrim           play         273.0  0
1  151603712                   Fallout 4       purchase           1.0  0
2  151603712                   Fallout 4           play          87.0  0
3  151603712                       Spore       purchase           1.0  0
4  151603712                       Spore           play          14.9  0

In [15]:
data.isnull().sum()

user_id           0
game_title        0
ownership_type    0
hours_played      0
x                 0
dtype: int64

### Exact duplicate - Index of the rows

In [16]:
def check_duplicate(df):
    check_list = df[df.duplicated()].index
    if check_list.empty:
        print("no duplicates")
    else:
        print("duplicate found")
        return check_list

In [17]:
duplicate_index = list(check_duplicate(data))
print(duplicate_index)

duplicate found
[1967, 1969, 1971, 2723, 2725, 2727, 3128, 3555, 3561, 3574, 4042, 4043, 4045, 4230, 5443, 6191, 7462, 7463, 7464, 8436, 8689, 9392, 11581, 12326, 12327, 12328, 12506, 12508, 12510, 12512, 13618, 13619, 13620, 13966, 13967, 13969, 13971, 15253, 15254, 15255, 15257, 15562, 15575, 15982, 16227, 16229, 16231, 16233, 18361, 18458, 18460, 18462, 18913, 20236, 20687, 20688, 20689, 22328, 22330, 22332, 22541, 24265, 24267, 24269, 24892, 24894, 24895, 25479, 26545, 26546, 26547, 26549, 27129, 27131, 27133, 27135, 27598, 28698, 28699, 28701, 28965, 28966, 28967, 29795, 29797, 29799, 29801, 30576, 30771, 30772, 30773, 30774, 31156, 33590, 33914, 34018, 34227, 35157, 35159, 35161, 35188, 35190, 35191, 35192, 36715, 36716, 36717, 36718, 37331, 37332, 37333, 37334, 38857, 39329, 39331, 39333, 40115, 41375, 41376, 41377, 43111, 43838, 43839, 43840, 44005, 44007, 44009, 44133, 44135, 44137, 44139, 44506, 44507, 45190, 45191, 45192, 45741, 47755, 47756, 47758, 48081, 48082, 49195, 50179, 51790, 51792, 51794, 52476, 52478, 52480, 53425, 53426, 53428, 53430, 53751, 55290, 55292, 55294, 55296, 55640, 55641, 55643, 55856, 55857, 55858, 56959, 57492, 57493, 57494, 59189, 59464, 59465, 60301, 61073, 61475, 61476, 61478, 62113, 62115, 62117, 62119, 63325, 63531, 63741, 63743, 63745, 63747, 64736, 64739, 64740, 65169, 65180, 65181, 65183, 65185, 67000, 67099, 67101, 67102, 67229, 67382, 67384, 67386, 67772, 67774, 67776, 67900, 67902, 67904, 67906, 69043, 69045, 69047, 69049, 72268, 72270, 72272, 72274, 73065, 73067, 73069, 73071, 74677, 75033, 75034, 75036, 75274, 75275, 75277, 76532, 76533, 76535, 77646, 77648, 77650, 77652, 77970, 77972, 77974, 77976, 78649, 78650, 78652, 78669, 78671, 78673, 78675, 82286, 82532, 82563, 82565, 82567, 82569, 82805, 83138, 83139, 83140, 87157, 87159, 87161, 88018, 88132, 88388, 88394, 89215, 89610, 89727, 90024, 90717, 90718, 90719, 93137, 94703, 94705, 94707, 94952, 94976, 94978, 94980, 94982, 95164, 95165, 95852, 95854, 95855, 95954, 95956, 95958, 95960, 95999, 96001, 96003, 96005, 96415, 96964, 96966, 96968, 97214, 97216, 97218, 97220, 99497, 99499, 99501, 99503, 99504, 99506, 99508, 99738, 99740, 99742, 99744, 100899, 100901, 100903, 100905, 101658, 101660, 101662, 101664, 102038, 102541, 102543, 102545, 102547, 102745, 102747, 102749, 102856, 102857, 102859, 102959, 103525, 103526, 103527, 103529, 103835, 104763, 104817, 105441, 105442, 105444, 106364, 106389, 106412, 106582, 106604, 106626, 107009, 108860, 108862, 108863, 109261, 110135, 110137, 110139, 110459, 110461, 110463, 110464, 111308, 111309, 111310, 111384, 112069, 112070, 112304, 112306, 112308, 112310, 112618, 112620, 112622, 113412, 114696, 114929, 115172, 115174, 115176, 115178, 115716, 116150, 116151, 117397, 117398, 117399, 117400, 117896, 118998, 119000, 119002, 121124, 121126, 121128, 121318, 121320, 121322, 121324, 122032, 123548, 123550, 123552, 123847, 124578, 124580, 124582, 125005, 125007, 125009, 125060, 125062, 125064, 125066, 125549, 125551, 125553, 126797, 126799, 126801, 126803, 128295, 128997, 128999, 129001, 130481, 130483, 130485, 130487, 131425, 131427, 131429, 132048, 132049, 134084, 134678, 134679, 134680, 135905, 135907, 135909, 136468, 136469, 136470, 136471, 137052, 137054, 137056, 137983, 137984, 137985, 138030, 138198, 138200, 138202, 138204, 138769, 139605, 139607, 139609, 139990, 141577, 141579, 141581, 141583, 142361, 142904, 142906, 142908, 142910, 143373, 145467, 145469, 145471, 146058, 146059, 146060, 146113, 146115, 146117, 146119, 146295, 146681, 146714, 146716, 146754, 146756, 146758, 146760, 147323, 147324, 147325, 147645, 147647, 147649, 148041, 148397, 148399, 148400, 149004, 149005, 149007, 149009, 149485, 149486, 149487, 150018, 150448, 150863, 151891, 151907, 151909, 151911, 152049, 152288, 152289, 152521, 152870, 152872, 152874, 154015, 154017, 154019, 154021, 154805, 154806, 154808, 154907, 154908, 154910, 154912, 155007, 156035, 156437, 156439, 156441, 156463, 157202, 157264, 157266, 157268, 157424, 157583, 157584, 157585, 157586, 159036, 159037, 161017, 161019, 161021, 161068, 161644, 161646, 161648, 161650, 161836, 162091, 162098, 162579, 163765, 164171, 164172, 164554, 164746, 164747, 164748, 165114, 165115, 165116, 165118, 165298, 165299, 165300, 165301, 166308, 167053, 167082, 167182, 167692, 167694, 167696, 167698, 168131, 168133, 168135, 168137, 169083, 169117, 169119, 169120, 169121, 169911, 169912, 170261, 171107, 171110, 171130, 172419, 172420, 172421, 172422, 174624, 174625, 174626, 175065, 175067, 175069, 175737, 175808, 175810, 175812, 175814, 176568, 176569, 176570, 177161, 177952, 177954, 177956, 177958, 178442, 179968, 180994, 180995, 182000, 182002, 182004, 182006, 183427, 183428, 183429, 183700, 183702, 183704, 183875, 184044, 184046, 184048, 184512, 184514, 184516, 184533, 184535, 184537, 184539, 185432, 185703, 185704, 185706, 185707, 186585, 186586, 186587, 186777, 186779, 186783, 186785, 187224, 187225, 187227, 187229, 188025, 188026, 188211, 188213, 188215, 188343, 188344, 188345, 188347, 188866, 188867, 188868, 190661, 190663, 190665, 191719, 192740, 192742, 192744, 192818, 192820, 192822, 192824, 193034, 193036, 193037, 193041, 193042, 193043, 193044, 193549, 193574, 193576, 193578, 193580, 194034, 194036, 194038, 194385, 194387, 194389, 194391, 195516, 195820, 195822, 195823]

In [18]:
## REMOVING THE EXACT DUPLICATE ROWS
data = data.drop_duplicates(keep='first')

In [19]:
data

          user_id                  game_title ownership_type  hours_played  x
0       151603712  The Elder Scrolls V Skyrim           play         273.0  0
1       151603712                   Fallout 4       purchase           1.0  0
2       151603712                   Fallout 4           play          87.0  0
3       151603712                       Spore       purchase           1.0  0
4       151603712                       Spore           play          14.9  0
...           ...                         ...            ...           ... ..
199994  128470551                 Titan Souls           play           1.5  0
199995  128470551  Grand Theft Auto Vice City       purchase           1.0  0
199996  128470551  Grand Theft Auto Vice City           play           1.5  0
199997  128470551                        RUSH       purchase           1.0  0
199998  128470551                        RUSH           play           1.4  0

[199292 rows x 5 columns]

In [21]:
check_duplicate(data)

no duplicates

In [22]:
data['is_partial_duplicate'] = data.duplicated(subset=['user_id','game_title'], keep=False)
print(data)

          user_id                  game_title ownership_type  hours_played  x  \
0       151603712  The Elder Scrolls V Skyrim           play         273.0  0
1       151603712                   Fallout 4       purchase           1.0  0
2       151603712                   Fallout 4           play          87.0  0
3       151603712                       Spore       purchase           1.0  0
4       151603712                       Spore           play          14.9  0
...           ...                         ...            ...           ... ..
199994  128470551                 Titan Souls           play           1.5  0
199995  128470551  Grand Theft Auto Vice City       purchase           1.0  0
199996  128470551  Grand Theft Auto Vice City           play           1.5  0
199997  128470551                        RUSH       purchase           1.0  0
199998  128470551                        RUSH           play           1.4  0

        is_partial_duplicate
0                      False
1                       True
2                       True
3                       True
4                       True
...                      ...
199994                  True
199995                  True
199996                  True
199997                  True
199998                  True

[199292 rows x 6 columns]

### Remove partial duplicate - removed the ownership type == purchased

In [23]:
data_dedup = data.drop_duplicates(subset=['user_id', 'game_title'], keep= 'last')

In [24]:
data_dedup

,user_id,game_title,ownership_type,hours_played,x,is_partial_duplicate
0,151603712,The Elder Scrolls V Skyrim,play,273.0,0,False
2,151603712,Fallout 4,play,87.0,0,True
4,151603712,Spore,play,14.9,0,True
6,151603712,Fallout New Vegas,play,12.1,0,True
8,151603712,Left 4 Dead 2,play,8.9,0,True
...,...,...,...,...,...,...
199990,128470551,Fallen Earth,play,2.4,0,True
199992,128470551,Magic Duels,play,2.2,0,True
199994,128470551,Titan Souls,play,1.5,0,True
199996,128470551,Grand Theft Auto Vice City,play,1.5,0,True
199998,128470551,RUSH,play,1.4,0,True

In [25]:
user_id = data_dedup['user_id']
user_id = user_id.unique()
print(user_id)

[151603712 187131847  59945701 ... 176449171 221315846 128470551]

In [26]:
# printing whole data of specific value of specific colu
data_dedup[data_dedup['user_id'] == user_id[2]]

,user_id,game_title,ownership_type,hours_played,x,is_partial_duplicate
68,59945701,Ultra Street Fighter IV,play,238.0,0,True
70,59945701,FINAL FANTASY XIII,play,84.0,0,True
72,59945701,The Elder Scrolls V Skyrim,play,58.0,0,True
74,59945701,Sid Meier's Civilization V,play,22.0,0,True
76,59945701,L.A. Noire,play,13.8,0,True
78,59945701,Company of Heroes Tales of Valor,play,10.2,0,True
80,59945701,7 Days to Die,play,7.8,0,True
82,59945701,Divekick,play,7.0,0,True
84,59945701,FINAL FANTASY VII,play,5.2,0,True
86,59945701,Orcs Must Die! 2,play,4.8,0,True
88,59945701,Killing Floor,play,3.4,0,True
90,59945701,Company of Heroes,play,3.2,0,True
92,59945701,Bastion,play,2.8,0,True
94,59945701,Undertale,play,2.6,0,True
96,59945701,Counter-Strike Global Offensive,play,2.3,0,True
98,59945701,Orcs Must Die!,play,0.7,0,True
100,59945701,THE KING OF FIGHTERS XIII STEAM EDITION,play,0.6,0,True
102,59945701,GUILTY GEAR XX ACCENT CORE PLUS R,play,0.5,0,True
104,59945701,Skullgirls,play,0.4,0,True
106,59945701,Assassin's Creed II,play,0.3,0,True
108,59945701,Company of Heroes Opposing Fronts,play,0.1,0,True
110,59945701,Team Fortress 2,play,0.1,0,True
111,59945701,Guilty Gear X2 #Reload,purchase,1.0,0,False
112,59945701,Left 4 Dead 2,purchase,1.0,0,False
113,59945701,Psychonauts,purchase,1.0,0,False
114,59945701,Cities in Motion 2,purchase,1.0,0,False
115,59945701,Company of Heroes (New Steam Version),purchase,1.0,0,False
116,59945701,Company of Heroes 2,purchase,1.0,0,False
117,59945701,Fallout New Vegas,purchase,1.0,0,False
118,59945701,Fallout New Vegas Courier's Stash,purchase,1.0,0,False
119,59945701,Fallout New Vegas Dead Money,purchase,1.0,0,False
120,59945701,Fallout New Vegas Honest Hearts,purchase,1.0,0,False
121,59945701,Garry's Mod,purchase,1.0,0,False
122,59945701,Killing Floor Mod Defence Alliance 2,purchase,1.0,0,False
123,59945701,Magicka,purchase,1.0,0,False
124,59945701,Magicka Vietnam,purchase,1.0,0,False
125,59945701,Natural Selection 2,purchase,1.0,0,False
126,59945701,Psychonauts Demo,purchase,1.0,0,False
127,59945701,Sanctum,purchase,1.0,0,False
128,59945701,Sanctum 2,purchase,1.0,0,False
129,59945701,Serious Sam 3 BFE,purchase,1.0,0,False
130,59945701,Skullgirls Endless Beta,purchase,1.0,0,False
131,59945701,Skyrim High Resolution Texture Pack,purchase,1.0,0,False

In [27]:
data_dedup.drop(columns="is_partial_duplicate")

          user_id                  game_title ownership_type  hours_played  x
0       151603712  The Elder Scrolls V Skyrim           play         273.0  0
2       151603712                   Fallout 4           play          87.0  0
4       151603712                       Spore           play          14.9  0
6       151603712           Fallout New Vegas           play          12.1  0
8       151603712               Left 4 Dead 2           play           8.9  0
...           ...                         ...            ...           ... ..
199990  128470551                Fallen Earth           play           2.4  0
199992  128470551                 Magic Duels           play           2.2  0
199994  128470551                 Titan Souls           play           1.5  0
199996  128470551  Grand Theft Auto Vice City           play           1.5  0
199998  128470551                        RUSH           play           1.4  0

[128804 rows x 5 columns]